cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'blackfireio/homebrew-blackfire'
tap 'homebrew/cask-fonts'
tap 'shivammathur/php'

brew 'coreutils'
brew 'ack'
brew 'go'
brew 'grc'
brew 'node'
brew 'nvm'
brew 'readline'
brew 'wget'
brew 'yarn'
brew 'nmap'
brew 'youtube-dl'
brew 'tree'
brew 'mas'
brew 'shivammathur/php/php@8.0'
brew 'pkg-config'
brew 'imagemagick'
brew 'composer'
brew 'mailhog'
brew 'watchman'
brew 'gh'
brew 'fd'
brew 'bat'
brew 'jq'
brew 'watchman'
brew 'react-native-cli'
brew 'mackup'
brew 'antigen'

cask 'zoom'
cask 'postman'
cask 'tuple'
cask 'hyper'
cask 'dropbox'
cask '1password'
cask 'bettertouchtool'
cask 'karabiner-elements'
cask 'spotify'
cask 'sublime-text'
cask 'slack'
cask 'phpstorm'
cask 'whatsapp'
cask 'telegram'
cask 'the-unarchiver'
cask 'mplayerx'
cask 'sip'
cask 'google-chrome'
cask 'aerial'
cask 'font-fira-code'
cask 'visual-studio-code'
cask 'notion'
cask 'runjs'
cask 'sourcetree'

# Gaming
cask 'nvidia-geforce-now'
cask 'steam'

# Quick look plugins
cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'qlprettypatch'
cask 'quicklook-csv'

# App Store applications
mas "Todoist", id: 585829637
mas "Xcode", id: 497799835
