cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'blackfireio/homebrew-blackfire'
tap 'homebrew/cask-fonts'

brew 'coreutils'
brew 'ack'
brew 'go'
brew 'grc'
brew 'node'
brew 'nvm'
brew 'readline'
brew 'wget'
brew 'yarn'
brew 'nmap'
brew 'youtube-dl'
brew 'tree'
brew 'mas'
brew 'php@7.3'
brew 'composer'
brew 'watchman'
brew 'bower'
brew 'blackfire-agent'
brew 'ansible'
brew 'hub'
brew 'fd'
brew 'bat'
brew 'jq'
brew 'watchman'
brew 'react-native-cli'
brew 'mackup'

cask 'transmission'
cask 'hyper'
cask 'dropbox'
cask '1password'
cask 'bettertouchtool'
cask 'karabiner-elements'
cask 'spotify'
cask 'sublime-text'
cask 'vagrant'
cask 'slack'
cask 'steam'
cask 'phpstorm'
cask 'whatsapp'
cask 'telegram'
cask 'querious'
cask 'sketch'
cask 'the-unarchiver'
cask 'teamviewer'
cask 'mplayerx'
cask 'sip'
cask 'google-chrome'
cask 'aerial'
cask 'font-fira-code'
cask 'android-studio'
cask 'visual-studio-code'
cask 'notion'
cask 'runjs'
cask 'docker'
cask 'java'
cask 'tweeten'

# Quick look plugins
cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'qlprettypatch'
cask 'quicklook-csv'

# App Store applications
mas "Spark", id: 1176895641
mas "Todoist", id: 585829637
mas "Xcode", id: 497799835
